BACKGROUND = r"assets\Background\background.png"
BACKGROUND_WALL1 = r"assets\Background\background-walls1.png"
BACKGROUND_WALL2 = r"assets\Background\background-walls2.png"
BACKGROUND_WALL3 = r"assets\Background\background-walls3.png"
BACKGROUND_WALL4 = r"assets\Background\background-walls4.png"
BUSH = r"assets\Background\Bush.png"

PLAYER_TANK = r"assets\playerTank.png"
ENEMY_TANK = r"assets\enemyTank.png"
BULLET = r"assets\Bullet.png"